# Generated by Django 5.2 on 2026-02-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_alter_job_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
