# Generated by Django 5.2 on 2026-02-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_alter_employerprofile_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='description',
        ),
        migrations.AddField(
            model_name='company',
            name='company_overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_highlights',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('resume_screening', 'Resume Screening'), ('recruiter_review', 'Recruiter Review'), ('shortlisted', 'Shortlisted'), ('interview_called', 'Interview Called'), ('offered', 'Offered'), ('rejected', 'Rejected'), ('hired', 'Hired'), ('withdrawn', 'Withdrawn')], default='applied', max_length=30),
        ),
    ]
