# Generated by Django 6.0.2 on 2026-02-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0008_conversation_initiated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HelpTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RaiseTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Jobseeker', 'Jobseeker'), ('Employer', 'Employer')], max_length=50)),
                ('subject', models.CharField(choices=[("Broken 'Apply' Button/Application Failure", "Broken 'Apply' Button/Application Failure"), ('File Upload/Resume Parsing Errors', 'File Upload/Resume Parsing Errors'), ('Outdated or Ghost Job Listings', 'Outdated or Ghost Job Listings'), ('Incorrect/Irrelevant Search Results & Filters', 'Incorrect/Irrelevant Search Results & Filters'), ('Profile Update/Saved Data Not Saving', 'Profile Update/Saved Data Not Saving'), ('Application Status Unchanged/Limbo', 'Application Status Unchanged/Limbo'), ('Broken Job Alerts & Notifications', 'Broken Job Alerts & Notifications'), ('Login/Registration Issues (Social Login Bugs)', 'Login/Registration Issues (Social Login Bugs)'), ('Site Incompatibility/Non-Responsive Mobile Layout', 'Site Incompatibility/Non-Responsive Mobile Layout'), ('Duplicate Job Listings (Spam)', 'Duplicate Job Listings (Spam)'), ('Others', 'Others')], max_length=255)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tickets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
